### ISSUE TITLE
Error: get blocks/0: connect ECONNREFUSED 127.0.0.1:8669

### ISSUE THREAD

**Issue by luukfroling** [vechain/connex#111]
`const fw = require('@vechain/connex-framework');
const cd = require('@vechain/connex-driver');

const net = new cd.SimpleNet('http://localhost:8669/')
console.log(net);
let driver; 
cd.Driver.connect(net).then(result => {
  driver = result;
})`

getting this error 

`eturn new Error(`${err.config.method} ${err.config.url}: ${err.message}`);
               ^

Error: get blocks/0: connect ECONNREFUSED 127.0.0.1:8669
    at convertError (C:\Users\luukf\node_modules\@vechain\connex-driver\dist\simple-net.js:77:16)
    at SimpleNet.<anonymous> (C:\Users\luukf\node_modules\@vechain\connex-driver\dist\simple-net.js:48:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\luukf\node_modules\@vechain\connex-driver\dist\simple-net.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by libotony** [comment]
You need a [thor](https://github.com/vechain/thor) node running as an API endpoint of the `driver`.
